### ISSUE TITLE
Change background color of field groups 

### ISSUE THREAD

**Issue by trinef** [DekodeInteraktiv/hogan-core#10]
Changing background color of class "acf-field-flexible-content" or "layout" makes it more clear where one module ends and another begins. Screenshot ex: http://d.pr/i/CWg3TY and https://d.pr/i/mmINQp

**Comment by soverasen** [comment]
```css

**Comment by soverasen** [comment]
sdf

**Comment by soverasen** [comment]
Jeg liker tanken. Her er mitt forslag:
![screen shot 2017-10-27 at 09 32 08](https://user-images.githubusercontent.com/16900754/32092840-63afe162-bafa-11e7-9a9b-bdad248883f1.png)

```css
.acf-field-flexible-content {
  background-color: #ccc;
}

.acf-field-flexible-content .layout {
  border: solid 1px #999;
}
```
